[package]
name = "bifurcation"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfaR_wrapper = {git = "https://github.com/MoinSebi/gfaR_wrapper"}
